name: Build, Lint, and Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn allow-scripts
      - run: yarn build
      - run: yarn lint
      - run: yarn test
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
